dist: xenial
cache:
  directories:
    - download
language: python
env:
  - VERSION=2.9.2 MD5=82db6a62febd8c2976d75b8bd5513315
  - VERSION=3.2.1 MD5=489ceea09aa6c78bde5c2241f9da742d
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - ./install-hdfs.sh
  - pip install codecov
install:
  - pip install -e .
  - pip install --upgrade -r dev_requirements.txt
script: PATH=hadoop/bin:$PATH PYTHONHASHSEED=random pytest
after_success: codecov
