sudo: required
dist: trusty
language: python
env:
  - CDH=cdh5
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy-5.7.1"
  - "pypy3.3-5.5-alpha"
before_install:
  - ./install-hdfs.sh
  - pip install codecov
install:
  - pip install -e .
  - pip install -r dev_requirements.txt
script: py.test
after_success: codecov
