dist: xenial
cache:
  directories:
    - download
language: python
env:
  - VERSION=2.6.5 MD5=967c24f3c15fcdd058f34923e92ce8ac
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
before_install:
  - ./install-hdfs.sh
  - pip install codecov
install:
  - pip install -e .
  - pip install --upgrade -r dev_requirements.txt
script: PATH=hadoop/bin:$PATH PYTHONHASHSEED=random pytest
after_success: codecov
