dist: xenial
language: python
env:
  - CDH=cdh5
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
before_install:
  - ./install-hdfs.sh
  - pip install codecov
install:
  - pip install -e .
  - pip install --upgrade -r dev_requirements.txt
script: PYTHONHASHSEED=random pytest
after_success: codecov
